### ISSUE TITLE
85C issue?

### ISSUE THREAD

**Issue by ericnev** [Gbertaz/NonBlockingDallas#11]
I'm hitting the "always returns 85C" issue myself, and I'm curious what I'm doing wrong - the DallasTemperature library (blocking) is working as intended, in fact if I call it RIGHT before my non blocking setup, it returns correctly, but my callbacks return nothing but 85C after following the guide here.

**Comment by ericnev** [comment]
Was a parasitic power issue.

**Comment by neno-research** [comment]
> Was a parasitic power issue.

I am getting this see image, what might be the issue?

![Image](https://github.com/user-attachments/assets/2f79c94e-05c9-4ce8-88b4-5319dc2b5cbd)
