### ISSUE TITLE
Feature request: access the number of devices detected on the bus

### ISSUE THREAD

**Issue by baronvertigovongrahamthesecondofsealand** [Gbertaz/NonBlockingDallas#14]
Looks like the variable needed in the library is private. Could this value be exposed, please?

**Comment by oopen** [comment]
In my pull request https://github.com/Gbertaz/NonBlockingDallas/pull/13 this parameter become readable by calling function 
`uint8_t getSensorsCount();`

Merge request is pending.

**Comment by Gbertaz** [comment]
@baronvertigovongrahamthesecondofsealand @oopen merged! 👍

**Comment by baronvertigovongrahamthesecondofsealand** [comment]
Wonderful, thanks chaps!
