### ISSUE TITLE
Missing examples from Library

### ISSUE THREAD

**Issue by awardblvr** [Gbertaz/NonBlockingDallas#5]
Missing example for how to read multiple sensors from a single wire AND...
HOW to assign addresses in the array so that a specific sensor can be associated with a particular index.

**Comment by Gbertaz** [comment]
Hi @awardblvr, [TemperatureReading.ino](https://github.com/Gbertaz/NonBlockingDallas/blob/master/examples/TemperatureReading/TemperatureReading.ino) example already works with multiple sensors (up to 15). Callbacks are called for each sensor found on the bus...

Good point for the index, I might consider implementing it.

Thanks!
